require("plugConfig.treesitter")
require("plugConfig.lsp")
require("plugConfig.cmp")
require("plugConfig.telescope")
require("plugConfig.neoclip")
require("plugConfig.bufferline")
require("plugConfig.lualine")
require("plugConfig.trouble")
require("plugConfig.autopairs")
require("plugConfig.glow")
require("plugConfig.hop")
require("plugConfig.indent-blankline")
require("plugConfig.toggleterm")
require("plugConfig.lir")
require("plugConfig.which-key")
require("plugConfig.keymapsPlug")
require("plugConfig.comment-box")

-- Markdown preview
vim.g.nvim_markdown_preview_theme = "solarized-dark"
