require("plugConfig.treesitter")
require("plugConfig.lsp")
require("plugConfig.cmp")
require("plugConfig.telescope")
require("plugConfig.neoclip")
require("plugConfig.alpha")
require("plugConfig.barbar")
require("plugConfig.lualine")
require("plugConfig.trouble")
require("plugConfig.autopairs")
require("plugConfig.glow")
require("plugConfig.hop")
require("plugConfig.indent-blankline")
require("plugConfig.toggleterm")
require("plugConfig.lir")
require("plugConfig.which-key")
require("plugConfig.keymapsPlug")
require("plugConfig.focus")

-- Where Cheat.sh give its results
vim.g.cheat_default_window_layout = "vertical_split"
