-- General configuration
require("impatient")
require("ludo.options")
require("ludo.plugins")
require("ludo.keymaps")
require("ludo.theme")

-- Plugins configuration
require("ludo.plugConfig.cmp")
require("ludo.plugConfig.lsp")
require("ludo.plugConfig.rust-tools")
require("ludo.plugConfig.telescope")
require("ludo.plugConfig.treesitter")
require("ludo.plugConfig.autopairs")
require("ludo.plugConfig.nvim-tree")
require("ludo.plugConfig.lualine")
require("ludo.plugConfig.toggleterm")
require("ludo.plugConfig.indent-blankline")
require("ludo.plugConfig.alpha")
require("ludo.plugConfig.barbar")
require("ludo.plugConfig.which-key")
require("ludo.plugConfig.glow")
require("ludo.plugConfig.surround")
require("ludo.plugConfig.neoclip")
