return {
  "shellRaining/hlchunk.nvim",
  event = { "UIEnter" },
  config = function()
    ---@diagnostic disable-next-line: missing-fields
    require("hlchunk").setup({
      ---@diagnostic disable-next-line: missing-fields
      indent = {
        enable = false,
      },
      ---@diagnostic disable-next-line: missing-fields
      blank = {
        enable = false,
      },
      exclude_filetypes = {
        aerial = true,
        dashboard = true,
        help = true,
        lspinfo = true,
        lspsagafinder = true,
        packer = true,
        checkhealth = true,
        man = true,
        mason = true,
        NvimTree = true,
        ["neo-tree"] = true,
        plugin = true,
        lazy = true,
        TelescopePrompt = true,
        [""] = true,
        alpha = true,
        toggleterm = true,
        sagafinder = true,
        sagaoutline = true,
        better_term = true,
        fugitiveblame = true,
        Trouble = true,
        qf = true,
        Outline = true,
        starter = true,
        NeogitPopup = true,
        NeogitStatus = true,
        DiffviewFiles = true,
        DiffviewFileHistory = true,
        DressingInput = true,
        spectre_panel = true,
        zsh = true,
        registers = true,
        startuptime = true,
        OverseerList = true,
        Navbuddy = true,
        noice = true,
        notify = true,
        ["dap-repl"] = true,
        saga_codeaction = true,
        sagarename = true,
        cmp_menu = true,
        ["null-ls-info"] = true,
        glowpreview = true,
        minifiles = true,
      },
    })
  end,
}
